// =============================================================================
// Tablecast — Session Panel Styles
// Styles object for the Session Planning & Management Panel.
// =============================================================================

export const sessionStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    overflow: "auto",
    padding: "1rem",
    gap: "1rem",
  },
  popoutContainer: {
    minHeight: "100vh",
    background: "var(--color-bg)",
  },
  panelTitle: {
    display: "flex",
    alignItems: "center",
    margin: 0,
    fontSize: "1.25rem",
    color: "var(--color-accent)",
  },
  panelSubtitle: {
    margin: "0.35rem 0 0",
    color: "var(--color-muted)",
    fontSize: "0.85rem",
  },
  listPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    maxWidth: "900px",
    margin: "0 auto",
    width: "100%",
  },
  listHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "1rem",
    flexWrap: "wrap",
  },
  filterRow: {
    display: "flex",
    gap: "0.5rem",
    flexWrap: "wrap",
  },
  filterChip: {
    minHeight: "44px",
    padding: "0.5rem 1rem",
    borderRadius: "999px",
    border: "1px solid rgba(255,255,255,0.08)",
    background: "transparent",
    color: "var(--color-muted)",
    cursor: "pointer",
  },
  filterChipActive: {
    background: "var(--color-accent-dim)",
    color: "var(--color-accent)",
    borderColor: "rgba(200, 151, 58, 0.35)",
  },
  cardList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  sessionCard: {
    textAlign: "left",
    padding: "1rem",
    borderRadius: "12px",
    border: "1px solid rgba(255,255,255,0.06)",
    background: "rgba(0,0,0,0.2)",
    color: "var(--color-text)",
    cursor: "pointer",
    minHeight: "44px",
  },
  cardTopRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "0.75rem",
    alignItems: "center",
  },
  cardTitle: {
    fontWeight: "bold",
    fontSize: "1rem",
  },
  cardMeta: {
    marginTop: "0.35rem",
    fontSize: "0.8rem",
    color: "var(--color-muted)",
  },
  detailPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    maxWidth: "900px",
    margin: "0 auto",
    width: "100%",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  backBtn: {
    display: "flex",
    alignItems: "center",
    gap: "0.35rem",
    background: "transparent",
    border: "none",
    color: "var(--color-muted)",
    cursor: "pointer",
    minHeight: "44px",
  },
  deleteBtn: {
    background: "rgba(239, 68, 68, 0.12)",
    border: "1px solid rgba(239, 68, 68, 0.25)",
    color: "var(--color-danger)",
    borderRadius: "8px",
    padding: "0.5rem",
    cursor: "pointer",
    minHeight: "44px",
    minWidth: "44px",
  },
  detailMeta: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  titleInput: {
    width: "100%",
    fontSize: "1.2rem",
    fontWeight: "bold",
    padding: "0.75rem",
    minHeight: "44px",
  },
  detailTitle: {
    margin: 0,
    color: "var(--color-accent)",
  },
  dateLine: {
    margin: 0,
    color: "var(--color-muted)",
  },
  metaRow: {
    display: "flex",
    gap: "0.75rem",
    flexWrap: "wrap",
  },
  metaField: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    flex: "1 1 140px",
    fontSize: "0.8rem",
    color: "var(--color-muted)",
  },
  numberInput: {
    minHeight: "44px",
    padding: "0.5rem",
  },
  dateInput: {
    minHeight: "44px",
    padding: "0.5rem",
  },
  statusBadgeRow: {
    display: "flex",
    gap: "0.75rem",
    alignItems: "center",
    flexWrap: "wrap",
  },
  statusBadge: {
    display: "inline-flex",
    padding: "0.25rem 0.6rem",
    borderRadius: "999px",
    fontSize: "0.75rem",
    fontWeight: "bold",
    letterSpacing: "0.04em",
  },
  visibilityToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.35rem",
    color: "var(--color-muted)",
    fontSize: "0.85rem",
    cursor: "pointer",
    minHeight: "44px",
  },
  lifecycleRow: {
    display: "flex",
    gap: "0.5rem",
    flexWrap: "wrap",
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    padding: "1rem",
    borderRadius: "12px",
    border: "1px solid rgba(255,255,255,0.06)",
    background: "rgba(0,0,0,0.15)",
  },
  sectionHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "0.5rem",
  },
  sectionTitle: {
    margin: 0,
    fontSize: "1rem",
    color: "var(--color-accent)",
  },
  textarea: {
    width: "100%",
    minHeight: "140px",
    padding: "0.75rem",
    resize: "vertical",
    fontFamily: "inherit",
  },
  markdownPreview: {
    padding: "0.75rem",
    borderRadius: "8px",
    background: "rgba(0,0,0,0.2)",
    minHeight: "60px",
  },
  togglePreviewBtn: {
    background: "transparent",
    border: "1px solid rgba(255,255,255,0.1)",
    color: "var(--color-muted)",
    borderRadius: "8px",
    padding: "0.35rem 0.75rem",
    cursor: "pointer",
    minHeight: "44px",
  },
  checklist: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  checklistItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  checkBtn: {
    width: "28px",
    height: "28px",
    borderRadius: "6px",
    border: "1px solid rgba(255,255,255,0.15)",
    background: "transparent",
    color: "var(--color-accent)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  checkBtnDone: {
    background: "rgba(34, 197, 94, 0.2)",
    borderColor: "rgba(34, 197, 94, 0.35)",
  },
  checklistText: {
    flex: 1,
    fontSize: "0.95rem",
  },
  checklistDone: {
    textDecoration: "line-through",
    color: "var(--color-muted)",
  },
  removeCheckBtn: {
    background: "transparent",
    border: "none",
    color: "var(--color-muted)",
    cursor: "pointer",
    minWidth: "44px",
    minHeight: "44px",
  },
  addChecklistForm: {
    display: "flex",
    gap: "0.5rem",
  },
  checklistInput: {
    flex: 1,
    minHeight: "44px",
    padding: "0.5rem 0.75rem",
  },
  linkedGroups: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  linkedGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  linkedGroupTitle: {
    fontSize: "0.8rem",
    color: "var(--color-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  linkedItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.35rem",
    background: "rgba(200, 151, 58, 0.08)",
    border: "1px solid rgba(200, 151, 58, 0.2)",
    color: "var(--color-text)",
    borderRadius: "8px",
    padding: "0.5rem 0.75rem",
    cursor: "pointer",
    minHeight: "44px",
    width: "fit-content",
  },
  pickerSection: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    marginTop: "0.5rem",
  },
  pickerGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  pickerLabel: {
    fontSize: "0.8rem",
    color: "var(--color-muted)",
  },
  pickerList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    maxHeight: "160px",
    overflowY: "auto",
    padding: "0.5rem",
    borderRadius: "8px",
    background: "rgba(0,0,0,0.2)",
  },
  pickerItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    minHeight: "44px",
    fontSize: "0.9rem",
    cursor: "pointer",
  },
  primaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.35rem",
    minHeight: "44px",
    padding: "0.6rem 1rem",
    borderRadius: "8px",
    border: "1px solid rgba(200, 151, 58, 0.35)",
    background: "rgba(200, 151, 58, 0.15)",
    color: "var(--color-accent)",
    fontWeight: "bold",
    cursor: "pointer",
  },
  secondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.35rem",
    minHeight: "44px",
    padding: "0.6rem 1rem",
    borderRadius: "8px",
    border: "1px solid rgba(255,255,255,0.1)",
    background: "transparent",
    color: "var(--color-text)",
    cursor: "pointer",
  },
  linkBtn: {
    alignSelf: "flex-start",
    minHeight: "44px",
    padding: "0.5rem 0.75rem",
    borderRadius: "8px",
    border: "1px solid rgba(200, 151, 58, 0.25)",
    background: "transparent",
    color: "var(--color-accent)",
    cursor: "pointer",
  },
  mutedText: {
    color: "var(--color-muted)",
    fontSize: "0.9rem",
    margin: 0,
  },
  errorText: {
    color: "var(--color-danger)",
    fontSize: "0.85rem",
    margin: 0,
  },
  successText: {
    color: "var(--color-success)",
    fontSize: "0.85rem",
    margin: 0,
  },
  errorBanner: {
    padding: "0.75rem 1rem",
    borderRadius: "8px",
    background: "rgba(239, 68, 68, 0.12)",
    border: "1px solid rgba(239, 68, 68, 0.25)",
    color: "var(--color-danger)",
  },
  emptyState: {
    padding: "2rem 1rem",
    textAlign: "center",
  },
};
