// =============================================================================
// Tablecast — Wiki Panel Styles (Extracted from WikiPanel)
// All inline style objects for the Wiki panel components
// =============================================================================

const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    padding: "0.75rem",
    gap: "0.75rem",
    position: "relative",
  },
  /* DM split-pane layout */
  splitPaneLayout: {
    display: "flex",
    flexDirection: "row",
    height: "100%",
    gap: 0,
    overflow: "hidden",
    borderRadius: "8px",
    border: "1px solid var(--color-border-light)",
  },
  splitContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    minWidth: 0,
  },
  /* Top bar for DM wiki list view */
  wikiTopBar: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.6rem 0.75rem",
    borderBottom: "1px solid var(--color-border-light)",
    background: "rgba(0, 0, 0, 0.15)",
    flexShrink: 0,
  },
  menuBtn: {
    display: "none",
    background: "transparent",
    border: "1px solid var(--color-border-light)",
    borderRadius: "6px",
    color: "var(--color-muted)",
    cursor: "pointer",
    padding: "0.35rem",
    flexShrink: 0,
  },
  listView: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    gap: "0.75rem",
  },
  sectionTabsContainer: {
    display: "flex",
    borderRadius: "8px",
    overflow: "hidden",
    border: "1px solid rgba(255, 255, 255, 0.05)",
    background: "rgba(0, 0, 0, 0.2)",
    flexShrink: 0,
    overflowX: "auto",
  },
  sectionTabBtn: {
    flex: 1,
    minWidth: "100px",
    background: "transparent",
    border: "none",
    padding: "0.65rem 0.35rem",
    cursor: "pointer",
    fontSize: "0.78rem",
    fontWeight: 700,
    textAlign: "center",
    whiteSpace: "nowrap",
    transition: "all 0.2s",
  },
  searchBarContainer: {
    display: "flex",
    position: "relative",
    flexShrink: 0,
    gap: "0.5rem",
    flexWrap: "wrap",
  },
  npcAutocompleteWrapper: {
    flex: "1 1 100%",
    marginBottom: "0.25rem",
  },
  importInput: {
    padding: "0.6rem 1rem",
    fontSize: "0.85rem",
    width: "100%",
  },
  searchInput: {
    flex: 1,
    padding: "0.75rem 1rem",
    fontSize: "0.95rem",
    borderRadius: "0.5rem",
    border: "1px solid rgba(200, 151, 58, 0.25)",
    background: "rgba(0,0,0,0.3)",
    color: "var(--color-text)",
    outline: "none",
    minWidth: "180px",
  },
  clearBtn: {
    position: "absolute",
    top: "12px",
    background: "transparent",
    border: "none",
    color: "var(--color-muted)",
    fontSize: "0.95rem",
    cursor: "pointer",
    padding: "0 0.75rem",
  },
  createBtn: {
    padding: "0.6rem 1rem",
    background: "linear-gradient(135deg, var(--color-accent) 0%, var(--color-accent-dark) 100%)",
    border: "none",
    borderRadius: "6px",
    color: "var(--color-bg)",
    fontWeight: "bold",
    fontSize: "0.85rem",
    cursor: "pointer",
    minHeight: "44px",
    whiteSpace: "nowrap",
  },
  listScroll: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  articleCard: {
    padding: "0.85rem 1rem",
    borderRadius: "8px",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardTitle: {
    fontSize: "1.05rem",
    fontWeight: 600,
    color: "var(--color-accent)",
    margin: 0,
  },
  cardSubText: {
    fontSize: "0.75rem",
    color: "var(--color-muted)",
  },
  secretDot: {
    fontSize: "0.72rem",
    color: "var(--color-danger)",
    background: "rgba(235, 87, 87, 0.12)",
    border: "1px solid rgba(235, 87, 87, 0.2)",
    padding: "0.1rem 0.35rem",
    borderRadius: "3px",
  },
  cardPreview: {
    fontSize: "0.8rem",
    color: "var(--color-muted)",
    lineHeight: 1.4,
    margin: 0,
  },
  cardTags: {
    display: "flex",
    gap: "0.35rem",
    marginTop: "0.25rem",
  },
  cardTag: {
    fontSize: "0.65rem",
    background: "rgba(255, 255, 255, 0.04)",
    padding: "0.15rem 0.4rem",
    borderRadius: "4px",
    color: "var(--color-muted)",
    border: "1px solid rgba(255,255,255,0.04)",
  },
  infoText: {
    textAlign: "center",
    color: "var(--color-muted)",
    fontSize: "0.85rem",
    marginTop: "2rem",
  },
  errorText: {
    textAlign: "center",
    color: "var(--color-danger)",
    fontSize: "0.85rem",
    marginTop: "2.5rem",
  },

  /* Reader View */
  reader: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    borderRadius: "12px",
    overflow: "hidden",
  },
  readerHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.65rem 0.75rem",
    borderBottom: "1px solid rgba(255, 255, 255, 0.06)",
    background: "rgba(0,0,0,0.15)",
    flexShrink: 0,
  },
  npcOptionCard: {
    width: "100%",
    textAlign: "left",
    padding: "0.7rem 0.85rem",
    borderRadius: "6px",
    border: "1px solid rgba(255,255,255,0.08)",
    transition: "transform 0.15s, box-shadow 0.15s",
    minHeight: "44px",
  },
  backBtn: {
    padding: "0.45rem 0.85rem",
    borderRadius: "4px",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.1)",
    color: "var(--color-text)",
    cursor: "pointer",
    fontSize: "0.8rem",
    fontWeight: 600,
    minHeight: "44px",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "0.65rem",
  },
  dmControlsRow: {
    display: "flex",
    gap: "0.35rem",
  },
  editBtn: {
    padding: "0.45rem 0.75rem",
    borderRadius: "4px",
    background: "rgba(200, 151, 58, 0.1)",
    border: "1px solid rgba(200, 151, 58, 0.3)",
    color: "var(--color-accent)",
    cursor: "pointer",
    fontSize: "0.75rem",
    fontWeight: 600,
    minHeight: "44px",
  },
  deleteBtn: {
    padding: "0.45rem 0.75rem",
    borderRadius: "4px",
    background: "rgba(235, 87, 87, 0.08)",
    border: "1px solid rgba(235, 87, 87, 0.25)",
    color: "var(--color-danger)",
    cursor: "pointer",
    fontSize: "0.75rem",
    fontWeight: 600,
    minHeight: "44px",
  },
  readerMenuBtn: {
    background: "transparent",
    border: "1px solid var(--color-border-light)",
    borderRadius: "4px",
    color: "var(--color-muted)",
    cursor: "pointer",
    padding: "0.35rem 0.5rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "44px",
  },
  secretBadge: {
    fontSize: "0.65rem",
    background: "rgba(235, 87, 87, 0.12)",
    border: "1px solid rgba(235, 87, 87, 0.25)",
    color: "var(--color-danger)",
    padding: "0.15rem 0.4rem",
    borderRadius: "4px",
    fontWeight: 600,
  },
  timeBadge: {
    fontSize: "0.65rem",
    color: "var(--color-muted)",
  },
  readerScroll: {
    flex: 1,
    overflowY: "auto",
    padding: "1.25rem",
  },
  linkedSessionBadge: {
    display: "inline-flex",
    alignItems: "center",
    marginBottom: "0.75rem",
    padding: "0.35rem 0.75rem",
    borderRadius: "999px",
    border: "1px solid rgba(200, 151, 58, 0.3)",
    background: "rgba(200, 151, 58, 0.12)",
    color: "var(--color-accent)",
    fontSize: "0.75rem",
    fontWeight: 600,
    cursor: "pointer",
    minHeight: "44px",
  },
  articleTitle: {
    fontSize: "1.5rem",
    fontWeight: 700,
    color: "var(--color-accent)",
    marginBottom: "0.5rem",
    lineHeight: 1.25,
    margin: 0,
  },
  npcBioHeader: {
    fontSize: "1.1rem",
    fontWeight: 700,
    color: "var(--color-accent)",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    paddingBottom: "0.35rem",
    marginTop: "1.5rem",
    marginBottom: "0.75rem",
  },
  npcBioDetails: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    marginTop: "0.5rem",
  },
  npcBioSection: {
    padding: "0.8rem 1rem",
    borderRadius: "6px",
    background: "rgba(255, 255, 255, 0.02)",
    borderLeft: "3px solid var(--color-accent)",
  },
  npcBioSectionTitle: {
    fontSize: "0.85rem",
    fontWeight: "bold",
    color: "var(--color-accent)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    margin: "0 0 0.4rem 0",
  },
  npcBioText: {
    fontSize: "0.9rem",
    lineHeight: "1.45",
  },
  tagList: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.35rem",
    marginBottom: "1.25rem",
  },
  tag: {
    fontSize: "0.7rem",
    background: "rgba(200, 151, 58, 0.08)",
    border: "1px solid rgba(200, 151, 58, 0.2)",
    padding: "0.2rem 0.5rem",
    borderRadius: "4px",
    color: "var(--color-accent)",
  },
  contentBody: {
    fontSize: "0.95rem",
    lineHeight: 1.6,
  },

  /* Workspace Editor */
  editor: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    borderRadius: "12px",
    overflow: "hidden",
  },
  editorHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.65rem 0.75rem",
    borderBottom: "1px solid rgba(255, 255, 255, 0.06)",
    background: "rgba(0,0,0,0.15)",
    flexShrink: 0,
  },
  editorTitle: {
    fontSize: "1.15rem",
    fontWeight: 700,
    color: "var(--color-accent)",
    margin: 0,
  },
  editorHeaderActions: {
    display: "flex",
    gap: "0.5rem",
  },
  saveBtn: {
    padding: "0.45rem 1rem",
    borderRadius: "4px",
    background: "linear-gradient(135deg, var(--color-accent) 0%, var(--color-accent-dark) 100%)",
    border: "none",
    color: "var(--color-bg)",
    cursor: "pointer",
    fontSize: "0.8rem",
    fontWeight: 700,
    minHeight: "44px",
  },
  editorBody: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "1rem",
    gap: "1.25rem",
    overflowY: "auto",
  },
  editorErrorText: {
    color: "var(--color-danger)",
    fontSize: "0.8rem",
    background: "rgba(235, 87, 87, 0.08)",
    border: "1px solid rgba(235, 87, 87, 0.2)",
    padding: "0.5rem",
    borderRadius: "4px",
    margin: 0,
  },

  formRow: {
    display: "flex",
    alignItems: "flex-end",
    gap: "1rem",
    flexWrap: "wrap",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  label: {
    fontSize: "0.75rem",
    color: "var(--color-muted)",
    fontWeight: 600,
  },
  input: {
    padding: "0.55rem 0.75rem",
    fontSize: "0.85rem",
  },
  select: {
    padding: "0.55rem 0.75rem",
    fontSize: "0.85rem",
    background: "rgba(0,0,0,0.3)",
    color: "var(--color-text)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: "6px",
    outline: "none",
    cursor: "pointer",
  },
  checkboxGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0.45rem",
    minHeight: "38px",
  },
  checkbox: {
    cursor: "pointer",
    width: "16px",
    height: "16px",
    accentColor: "var(--color-accent)",
  },
  checkboxLabel: {
    fontSize: "0.85rem",
    color: "var(--color-text)",
    cursor: "pointer",
    userSelect: "none",
  },
  tagChipsContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.35rem",
    alignItems: "center",
    padding: "0.4rem 0.6rem",
  },
  editorTagChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.25rem",
    fontSize: "0.72rem",
    background: "rgba(200, 151, 58, 0.12)",
    border: "1px solid rgba(200, 151, 58, 0.3)",
    padding: "0.15rem 0.45rem",
    borderRadius: "4px",
    color: "var(--color-accent)",
  },
  tagChipRemove: {
    background: "transparent",
    border: "none",
    color: "var(--color-accent)",
    cursor: "pointer",
    fontSize: "0.65rem",
    padding: "0.1rem",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  tagInputField: {
    flex: 1,
    minWidth: "120px",
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--color-text)",
    fontSize: "0.85rem",
    padding: "0.1rem 0",
  },
  tabsContainer: {
    display: "flex",
    borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
    gap: "1rem",
    flexShrink: 0,
  },
  tabBtn: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    fontSize: "0.85rem",
    fontWeight: 600,
    padding: "0.45rem 0.25rem",
  },
  workspaceWriteContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    minHeight: "280px",
  },
  toolbar: {
    display: "flex",
    gap: "0.35rem",
    alignItems: "center",
    background: "rgba(0,0,0,0.2)",
    padding: "0.35rem",
    borderRadius: "6px",
    flexWrap: "wrap",
    border: "1px solid rgba(255, 255, 255, 0.04)",
  },
  toolbarBtn: {
    minWidth: "32px",
    height: "32px",
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.06)",
    borderRadius: "4px",
    color: "var(--color-text)",
    fontSize: "0.75rem",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  textarea: {
    flex: 1,
    resize: "none",
    minHeight: "220px",
    fontFamily: "Courier New, Courier, monospace",
    fontSize: "0.9rem",
    lineHeight: "1.45",
  },
  textareaMini: {
    padding: "0.55rem 0.75rem",
    fontSize: "0.85rem",
    resize: "vertical",
  },
  previewContainer: {
    flex: 1,
    overflowY: "auto",
    padding: "0.75rem",
    border: "1px solid rgba(255,255,255,0.04)",
    borderRadius: "6px",
    background: "rgba(0,0,0,0.15)",
    minHeight: "280px",
  },

  /* NPC editor section styles */
  editorSection: {
    display: "flex",
    flexDirection: "column",
    gap: "0.85rem",
  },
  subSectionTitle: {
    fontSize: "0.85rem",
    fontWeight: 700,
    color: "var(--color-accent)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
    paddingBottom: "0.25rem",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(130px, 1fr))",
    gap: "0.75rem",
  },
  abilityGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(6, 1fr)",
    gap: "0.5rem",
    "@media (max-width: 600px)": {
      gridTemplateColumns: "repeat(3, 1fr)",
    },
  },
  abilityBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "0.6rem 0.4rem",
    borderRadius: "8px",
    gap: "0.25rem",
  },
  abilityLabel: {
    fontSize: "0.65rem",
    fontWeight: 700,
    color: "var(--color-muted)",
  },
  abilityInput: {
    width: "45px",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid rgba(255,255,255,0.15)",
    textAlign: "center",
    color: "var(--color-text)",
    fontSize: "1rem",
    fontWeight: "bold",
    outline: "none",
    padding: "0.1rem 0",
  },
  abilityModBadge: {
    fontSize: "0.72rem",
    color: "var(--color-accent)",
    background: "rgba(200,151,58,0.1)",
    padding: "0.05rem 0.35rem",
    borderRadius: "4px",
    fontWeight: 600,
  },
  actionsHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  addActionBtn: {
    padding: "0.4rem 0.85rem",
    background: "rgba(200, 151, 58, 0.08)",
    border: "1px solid rgba(200,151,58,0.35)",
    borderRadius: "6px",
    color: "var(--color-accent)",
    fontSize: "0.75rem",
    fontWeight: 600,
    cursor: "pointer",
    minHeight: "36px",
  },
  actionsEditorList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.85rem",
  },
  actionItemBox: {
    borderRadius: "8px",
    padding: "0.85rem",
    background: "rgba(255,255,255,0.01)",
    display: "flex",
    flexDirection: "column",
    gap: "0.65rem",
  },
  removeActionBtn: {
    background: "transparent",
    border: "none",
    color: "var(--color-danger)",
    fontSize: "0.7rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  actionFieldsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 100px 140px",
    gap: "0.75rem",
  },
  actionIdxLabel: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "var(--color-muted)",
    margin: 0,
  },

  /* CATEGORY CHOICE MODAL */
  categoryPromptBox: {
    width: "100%",
    maxWidth: "520px",
    borderRadius: "12px",
    padding: "1.5rem",
    display: "flex",
    flexDirection: "column",
    gap: "1.25rem",
    background: "rgba(15, 14, 23, 0.95)",
    boxShadow: "0 10px 40px rgba(0,0,0,0.7)",
  },
  categoryPromptGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "0.75rem",
    marginTop: "0.5rem",
    "@media (max-width: 500px)": {
      gridTemplateColumns: "1fr",
    },
  },
  categoryPromptBtn: {
    padding: "1rem",
    borderRadius: "8px",
    background: "rgba(255, 255, 255, 0.02)",
    border: "1px solid rgba(255, 255, 255, 0.05)",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    gap: "0.35rem",
    transition: "all 0.2s",
  },
  categoryPromptIcon: {
    fontSize: "1.75rem",
    marginBottom: "0.25rem",
  },
  categoryPromptLabel: {
    fontSize: "0.95rem",
    fontWeight: "bold",
    color: "var(--color-accent)",
  },
  categoryPromptDesc: {
    fontSize: "0.7rem",
    color: "var(--color-muted)",
    lineHeight: 1.3,
  },

  /* MODAL OVERLAY STYLES */
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(5, 3, 10, 0.8)",
    backdropFilter: "blur(6px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
    padding: "1rem",
  },
  modalContent: {
    width: "100%",
    maxWidth: "400px",
    borderRadius: "10px",
    padding: "1.25rem",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    background: "var(--color-surface)",
    boxShadow: "0 10px 40px rgba(0,0,0,0.7)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    paddingBottom: "0.5rem",
  },
  modalTitle: {
    fontSize: "1rem",
    color: "var(--color-danger)",
    fontWeight: "bold",
    margin: 0,
  },
  modalCloseBtn: {
    background: "transparent",
    border: "none",
    color: "var(--color-muted)",
    fontSize: "1.1rem",
    cursor: "pointer",
  },
  modalBody: {
    fontSize: "0.85rem",
    lineHeight: 1.5,
    color: "var(--color-text)",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "0.5rem",
    borderTop: "1px solid rgba(255,255,255,0.06)",
    paddingTop: "0.75rem",
  },
  modalCancelBtn: {
    padding: "0.45rem 0.85rem",
    borderRadius: "4px",
    background: "transparent",
    border: "1px solid rgba(255,255,255,0.1)",
    color: "var(--color-text)",
    cursor: "pointer",
    fontSize: "0.75rem",
    fontWeight: 600,
    minHeight: "44px",
  },
  confirmDeleteBtn: {
    padding: "0.45rem 1rem",
    borderRadius: "4px",
    background: "rgba(235, 87, 87, 0.15)",
    border: "1px solid rgba(235, 87, 87, 0.35)",
    color: "var(--color-danger)",
    cursor: "pointer",
    fontSize: "0.75rem",
    fontWeight: 700,
    minHeight: "44px",
  },
  // NPC token image preview
  npcTokenPreview: {
    width: "64px",
    height: "64px",
    borderRadius: "8px",
    overflow: "hidden",
    border: "2px solid var(--color-accent)",
    flexShrink: 0,
    background: "var(--color-surface)",
  },
  npcTokenPreviewImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  // Auto-find button
  autoFindBtn: {
    padding: "0.3rem 0.75rem",
    borderRadius: "6px",
    background: "rgba(100, 180, 255, 0.1)",
    border: "1px solid rgba(100, 180, 255, 0.25)",
    color: "var(--color-accent)",
    cursor: "pointer",
    fontSize: "0.72rem",
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  // NPC token preset grid
  npcPresetGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.4rem",
  },
  npcPresetBtn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.2rem",
    padding: "0.3rem",
    borderRadius: "6px",
    background: "rgba(255,255,255,0.03)",
    cursor: "pointer",
    width: "60px",
  },
  npcPresetImg: {
    width: "40px",
    height: "40px",
    borderRadius: "4px",
    objectFit: "cover",
  },
  npcPresetLabel: {
    fontSize: "0.6rem",
    color: "var(--color-muted)",
    textAlign: "center",
    lineHeight: 1.1,
  },
};

export default styles;
