// =============================================================================
// Tablecast — Settings Panel Styles
// Styles object for the DM Settings & Cloud Backups Panel.
// =============================================================================

const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    padding: "1.25rem",
    overflowY: "auto",
    background: "var(--color-bg)",
    gap: "1.5rem",
  },
  header: {
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
    paddingBottom: "0.75rem",
  },
  title: {
    fontSize: "1.5rem",
    fontWeight: "bold",
    color: "var(--color-accent)",
    marginBottom: "0.25rem",
  },
  subtitle: {
    fontSize: "0.85rem",
    color: "var(--color-muted)",
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: "1.25rem",
    maxWidth: "600px",
    width: "100%",
    margin: "0 auto",
  },
  card: {
    borderRadius: "8px",
    padding: "1.25rem",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  cardTitle: {
    fontSize: "1.1rem",
    color: "var(--color-text)",
    fontWeight: "bold",
  },
  cardDesc: {
    fontSize: "0.85rem",
    color: "var(--color-muted)",
    lineHeight: "1.4",
  },
  codeInline: {
    fontFamily: "monospace",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    padding: "0.15rem 0.3rem",
    borderRadius: "3px",
    color: "var(--color-accent)",
    fontSize: "0.8rem",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "1.25rem",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.4rem",
  },
  label: {
    fontSize: "0.85rem",
    fontWeight: 600,
    color: "var(--color-text)",
  },
  input: {
    width: "100%",
    padding: "0.75rem",
    fontSize: "0.9rem",
  },
  helpText: {
    fontSize: "0.75rem",
    color: "var(--color-muted)",
    marginTop: "0.15rem",
  },
  backupBtn: {
    width: "100%",
    border: "none",
    borderRadius: "6px",
    fontWeight: "bold",
    fontSize: "0.95rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.4rem",
    transition: "all 0.2s",
  },
  secondaryBtn: {
    width: "100%",
    border: "1px solid rgba(200, 151, 58, 0.35)",
    borderRadius: "6px",
    background: "rgba(200, 151, 58, 0.08)",
    color: "var(--color-accent)",
    fontWeight: "bold",
    fontSize: "0.9rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s",
  },
  sourceCloud: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.4rem",
  },
  sourceChip: {
    minHeight: "44px",
    padding: "0.45rem 0.7rem",
    borderRadius: "6px",
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(255,255,255,0.03)",
    fontSize: "0.75rem",
    fontWeight: 700,
  },
  loadingSpinnerContainer: {
    display: "flex",
    alignItems: "center",
    gap: "0.6rem",
  },
  spinner: {
    width: "18px",
    height: "18px",
    border: "2px solid rgba(255,255,255,0.3)",
    borderTop: "2px solid var(--color-text)",
    borderRadius: "50%",
    animation: "shake 0.8s linear infinite",
  },
  statusBanner: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderRadius: "6px",
    padding: "1rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  bannerHeader: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  bannerIcon: {
    fontSize: "1.2rem",
  },
  bannerText: {
    fontWeight: "bold",
    fontSize: "0.95rem",
  },
  bannerMessage: {
    fontSize: "0.85rem",
    color: "var(--color-text)",
    lineHeight: "1.3",
  },
  detailsTable: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    background: "rgba(0, 0, 0, 0.2)",
    padding: "0.75rem",
    borderRadius: "6px",
    border: "1px solid rgba(255,255,255,0.03)",
  },
  detailsRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "0.8rem",
  },
  detailsLabel: {
    color: "var(--color-muted)",
  },
  detailsVal: {
    color: "var(--color-text)",
    fontFamily: "monospace",
    fontWeight: "bold",
  },
  consoleTitle: {
    fontSize: "0.85rem",
    fontWeight: "bold",
    color: "var(--color-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginTop: "0.5rem",
  },
  console: {
    background: "var(--color-bg)",
    border: "1px solid rgba(255, 255, 255, 0.05)",
    borderRadius: "6px",
    padding: "0.85rem",
    fontFamily: "Courier New, Courier, monospace",
    fontSize: "0.8rem",
    maxHeight: "180px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "0.4rem",
  },
  consoleStdout: {
    color: "var(--color-success)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
  },
  consoleStderr: {
    color: "var(--color-danger)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
  },
  consoleMuted: {
    color: "var(--color-muted)",
    fontStyle: "italic",
  },

  subTabNav: {
    display: "flex",
    padding: "0.5rem 0",
    gap: "0.5rem",
    marginTop: "0.5rem",
  },
  subTabBtn: {
    flex: 1,
    maxWidth: "200px",
    border: "none",
    borderRadius: "4px",
    fontSize: "0.8rem",
    fontWeight: 600,
    cursor: "pointer",
    padding: "0.45rem",
    transition: "all 0.2s",
    minHeight: "44px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.35rem",
  },
  configEditorContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    background: "rgba(0, 0, 0, 0.15)",
    padding: "1rem",
    borderRadius: "6px",
    border: "1px solid rgba(255, 255, 255, 0.05)",
    marginTop: "0.25rem",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(5, 3, 10, 0.8)",
    backdropFilter: "blur(6px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "1rem",
  },
  modalContent: {
    background: "rgba(15, 14, 23, 0.95)",
    border: "1px solid rgba(200, 151, 58, 0.35)",
    boxShadow: "0 0 30px rgba(200, 151, 58, 0.25)",
    borderRadius: "12px",
    maxWidth: "600px",
    width: "100%",
    maxHeight: "90vh",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "1.25rem",
    padding: "1.75rem",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
    paddingBottom: "0.75rem",
  },
  modalTitle: {
    fontSize: "1.25rem",
    fontWeight: "bold",
    color: "var(--color-accent)",
    margin: 0,
  },
  modalCloseBtn: {
    background: "transparent",
    border: "none",
    color: "var(--color-muted)",
    fontSize: "1.5rem",
    cursor: "pointer",
    lineHeight: 1,
  },
  tutorialContainer: {
    background: "rgba(0, 0, 0, 0.2)",
    padding: "1rem",
    borderRadius: "8px",
    border: "1px solid rgba(255, 255, 255, 0.03)",
    fontSize: "0.85rem",
    color: "var(--color-text)",
    lineHeight: "1.45",
  },
  copyGroup: {
    display: "flex",
    gap: "0.5rem",
    marginTop: "0.5rem",
  },
  copyInput: {
    flex: 1,
    background: "rgba(0,0,0,0.4)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "4px",
    padding: "0.45rem",
    fontSize: "0.75rem",
    color: "var(--color-text)",
    fontFamily: "monospace",
  },
  copyBtn: {
    padding: "0 0.75rem",
    background: "rgba(200, 151, 58, 0.15)",
    border: "1px solid rgba(200, 151, 58, 0.3)",
    borderRadius: "4px",
    color: "var(--color-accent)",
    fontSize: "0.75rem",
    fontWeight: "bold",
    cursor: "pointer",
    minHeight: "36px",
  },
};

export { styles };
