// =============================================================================
// Tablecast — Character Sheet Styles (Extracted from CharacterSheet)
// All inline style objects for the Character Sheet component
// =============================================================================

const styles = {
  sheet: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    gap: "0.5rem",
    padding: "0.5rem",
  },
  stateContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    color: "var(--color-muted)",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0.6rem 0.85rem",
    borderRadius: "8px",
    flexShrink: 0,
    background: "rgba(0,0,0,0.2)",
  },
  backBtn: {
    padding: "0.45rem 0.75rem",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "4px",
    color: "var(--color-text)",
    cursor: "pointer",
    fontSize: "0.8rem",
    fontWeight: 600,
  },
  headerStats: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  charName: {
    fontSize: "1.1rem",
    fontWeight: 700,
    color: "var(--color-accent)",
  },
  charSummary: {
    fontSize: "0.75rem",
    color: "var(--color-text)",
    opacity: 0.8,
  },
  saveBadge: {
    fontSize: "0.65rem",
    fontWeight: 600,
    minWidth: "60px",
    textAlign: "right",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  aiGenerateBtn: {
    padding: "0.45rem 0.75rem",
    background: "rgba(200, 151, 58, 0.12)",
    border: "1px solid rgba(200, 151, 58, 0.35)",
    borderRadius: "6px",
    color: "var(--color-accent)",
    cursor: "pointer",
    fontSize: "0.8rem",
    fontWeight: 700,
  },
  savingDot: { color: "var(--color-info)" },
  savedDot: { color: "var(--color-success)" },
  errorDot: { color: "var(--color-danger)" },

  detailsBlock: {
    display: "grid",
    gridTemplateColumns: "1.2fr 1fr",
    gap: "0.75rem",
    padding: "0.75rem",
    borderRadius: "8px",
    flexShrink: 0,
  },
  narrativeSection: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "0.5rem",
    padding: "0.75rem",
    borderRadius: "8px",
    flexShrink: 0,
  },
  narrativeCard: {
    display: "flex",
    flexDirection: "column",
    gap: "0.4rem",
  },
  narrativeHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "0.5rem",
  },
  narrativeLabel: {
    fontSize: "0.8rem",
    fontWeight: 700,
    color: "var(--color-muted)",
  },
  narrativeTextArea: {
    width: "100%",
    minHeight: "88px",
    resize: "vertical",
    padding: "0.6rem",
    background: "rgba(0,0,0,0.28)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: "6px",
    color: "var(--color-text)",
    fontSize: "0.85rem",
    outline: "none",
  },
  hpWidget: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  hpHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  blockLabel: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "var(--color-muted)",
  },
  hpValues: {
    fontSize: "0.85rem",
    fontWeight: 700,
  },
  hpBarContainer: {
    height: "6px",
    background: "rgba(0,0,0,0.4)",
    borderRadius: "3px",
    overflow: "hidden",
  },
  hpBar: {
    height: "100%",
    borderRadius: "3px",
    transition: "width 0.3s ease",
  },
  hpControls: {
    display: "flex",
    alignItems: "center",
    gap: "0.35rem",
    marginTop: "0.25rem",
  },
  hpBtn: {
    padding: "0.2rem 0.5rem",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "4px",
    color: "var(--color-text)",
    cursor: "pointer",
    fontSize: "0.75rem",
  },
  hpInput: {
    width: "42px",
    padding: "0.2rem",
    background: "rgba(0,0,0,0.3)",
    border: "1px solid rgba(255,255,255,0.1)",
    color: "var(--color-text)",
    textAlign: "center",
    borderRadius: "4px",
    fontSize: "0.8rem",
    outline: "none",
  },

  levelMaxHp: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "0.35rem",
  },
  miniInputGroup: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.2rem",
    flex: 1,
  },
  miniLabel: {
    fontSize: "0.65rem",
    color: "var(--color-muted)",
    fontWeight: 600,
  },
  miniInput: {
    width: "100%",
    maxWidth: "50px",
    padding: "0.35rem",
    background: "rgba(0,0,0,0.3)",
    border: "1px solid rgba(255,255,255,0.1)",
    color: "var(--color-text)",
    textAlign: "center",
    borderRadius: "4px",
    fontSize: "0.85rem",
    outline: "none",
  },
  profBonusBox: {
    width: "100%",
    maxWidth: "50px",
    padding: "0.35rem",
    background: "rgba(200, 151, 58, 0.08)",
    border: "1px solid rgba(200, 151, 58, 0.2)",
    color: "var(--color-accent)",
    textAlign: "center",
    borderRadius: "4px",
    fontSize: "0.85rem",
    fontWeight: "bold",
  },

  tabNav: {
    display: "flex",
    justifyContent: "space-around",
    borderBottom: "1px solid rgba(255, 255, 255, 0.06)",
    flexShrink: 0,
  },
  tabBtn: {
    background: "transparent",
    border: "none",
    padding: "0.5rem 0.25rem",
    fontSize: "0.85rem",
    cursor: "pointer",
  },
  scrollArea: {
    flex: 1,
    overflowY: "auto",
    padding: "0.25rem",
  },

  /* Stats View */
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "0.5rem",
    paddingBottom: "1rem",
  },
  statBox: {
    borderRadius: "8px",
    padding: "0.6rem",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
  },
  statNameLabel: {
    fontSize: "0.65rem",
    fontWeight: 700,
    color: "var(--color-muted)",
  },
  statModBtn: {
    background: "rgba(200, 151, 58, 0.08)",
    border: "1px solid rgba(200, 151, 58, 0.25)",
    borderRadius: "6px",
    color: "var(--color-accent)",
    fontSize: "1.4rem",
    fontWeight: 700,
    margin: "0.35rem 0",
    width: "54px",
    height: "42px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  statInput: {
    width: "38px",
    border: "none",
    background: "rgba(255,255,255,0.03)",
    textAlign: "center",
    color: "var(--color-text)",
    fontSize: "0.8rem",
    outline: "none",
    borderRadius: "3px",
  },
  saveProfRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.3rem",
    marginTop: "0.45rem",
    fontSize: "0.65rem",
    color: "var(--color-muted)",
    width: "100%",
    justifyContent: "center",
  },
  saveRollText: {
    background: "transparent",
    border: "none",
    color: "inherit",
    fontSize: "inherit",
    cursor: "pointer",
  },
  checkbox: {
    width: "13px",
    height: "13px",
    accentColor: "var(--color-accent)",
    cursor: "pointer",
  },

  /* Skills View */
  skillsList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
    paddingBottom: "1rem",
  },
  skillRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.55rem 0.75rem",
    borderRadius: "6px",
  },
  skillLeft: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  skillNameText: {
    fontSize: "0.85rem",
    fontWeight: 600,
  },
  skillAbilityTag: {
    fontSize: "0.6rem",
    color: "var(--color-muted)",
    background: "rgba(255,255,255,0.05)",
    padding: "0.1rem 0.3rem",
    borderRadius: "3px",
  },
  skillRollBtn: {
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    padding: "0.3rem 0.6rem",
    borderRadius: "4px",
    color: "var(--color-accent)",
    cursor: "pointer",
    fontSize: "0.8rem",
    fontWeight: 600,
  },

  /* Attacks View */
  attacksContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    paddingBottom: "1rem",
  },
  attackSubHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  subTitle: {
    fontSize: "0.95rem",
    color: "var(--color-accent)",
    fontWeight: 600,
  },
  addBtn: {
    padding: "0.35rem 0.65rem",
    background: "transparent",
    border: "1px solid var(--color-accent)",
    borderRadius: "4px",
    color: "var(--color-accent)",
    fontSize: "0.75rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  attacksList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  attackCard: {
    padding: "0.75rem",
    borderRadius: "6px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  atkInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "0.2rem",
  },
  atkName: {
    fontSize: "0.85rem",
    fontWeight: 700,
    color: "var(--color-text)",
  },
  atkFormula: {
    fontSize: "0.75rem",
    color: "var(--color-muted)",
  },
  atkActions: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  atkRollBtn: {
    padding: "0.35rem 0.65rem",
    background: "rgba(200, 151, 58, 0.1)",
    border: "1px solid var(--color-border)",
    borderRadius: "4px",
    color: "var(--color-accent)",
    cursor: "pointer",
    fontSize: "0.75rem",
    fontWeight: 600,
  },
  deleteBtn: {
    background: "transparent",
    border: "none",
    color: "var(--color-danger)",
    opacity: 0.7,
    padding: "0.25rem 0.5rem",
    cursor: "pointer",
    fontSize: "0.95rem",
  },

  /* Inventory View */
  inventoryContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    paddingBottom: "1rem",
  },
  inventoryHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "0.75rem",
  },
  weightCard: {
    flex: 1,
    padding: "0.5rem 0.75rem",
    borderRadius: "6px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  weightLabel: {
    fontSize: "0.75rem",
    color: "var(--color-muted)",
  },
  weightValue: {
    fontSize: "0.85rem",
    fontWeight: "bold",
    color: "var(--color-text)",
  },
  itemList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.4rem",
  },
  itemCard: {
    padding: "0.6rem 0.75rem",
    borderRadius: "6px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  itemInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "0.15rem",
  },
  itemName: {
    fontSize: "0.85rem",
    fontWeight: 600,
  },
  itemDetails: {
    fontSize: "0.7rem",
    color: "var(--color-muted)",
  },

  /* Subforms */
  subForm: {
    padding: "1rem",
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    marginBottom: "0.5rem",
  },
  subFormTitle: {
    fontSize: "0.9rem",
    fontWeight: 700,
    color: "var(--color-accent)",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
    paddingBottom: "0.25rem",
  },
  subFormRow: {
    display: "flex",
    gap: "0.5rem",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.2rem",
    flex: 1,
  },
  subLabel: {
    fontSize: "0.7rem",
    color: "var(--color-muted)",
  },
  subInput: {
    width: "100%",
    padding: "0.45rem",
    fontSize: "0.85rem",
  },
  select: {
    background: "rgba(0,0,0,0.3)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: "4px",
    color: "var(--color-text)",
    padding: "0.45rem",
    fontSize: "0.85rem",
    outline: "none",
  },
  subBtnRow: {
    display: "flex",
    gap: "0.5rem",
    justifyContent: "flex-end",
    marginTop: "0.25rem",
  },
  subCancelBtn: {
    padding: "0.4rem 0.8rem",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "4px",
    color: "var(--color-text)",
    cursor: "pointer",
    fontSize: "0.8rem",
  },
  subSubmitBtn: {
    padding: "0.4rem 0.8rem",
    background: "var(--color-accent)",
    border: "none",
    borderRadius: "4px",
    color: "var(--color-bg)",
    fontWeight: "bold",
    cursor: "pointer",
    fontSize: "0.8rem",
  },

  /* Spells Tab */
  spellsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    paddingBottom: "1rem",
  },
  spellHeaderRow: {
    display: "flex",
    gap: "0.5rem",
    alignItems: "center",
  },
  spellAbilityGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.2rem",
    flex: 1,
  },
  spellLabel: {
    fontSize: "0.7rem",
    color: "var(--color-muted)",
    fontWeight: 600,
  },
  spellSelect: {
    background: "rgba(0,0,0,0.3)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: "6px",
    color: "var(--color-text)",
    padding: "0.45rem",
    fontSize: "0.85rem",
    outline: "none",
  },
  spellStatBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    background: "rgba(200,151,58,0.08)",
    border: "1px solid rgba(200,151,58,0.2)",
    borderRadius: "6px",
    padding: "0.4rem 0.7rem",
    minWidth: "60px",
  },
  spellStatLabel: {
    fontSize: "0.6rem",
    color: "var(--color-muted)",
    fontWeight: 600,
  },
  spellStatValue: {
    fontSize: "1.1rem",
    fontWeight: 700,
    color: "var(--color-accent)",
  },
  spellSectionTitle: {
    fontSize: "0.9rem",
    color: "var(--color-accent)",
    fontWeight: 600,
  },
  /* Spell Slots */
  spellSlotsSection: {
    padding: "0.6rem 0.75rem",
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  spellSlotsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  spellSmallBtn: {
    padding: "0.25rem 0.5rem",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "4px",
    color: "var(--color-muted)",
    cursor: "pointer",
    fontSize: "0.65rem",
  },
  spellSlotsGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  slotRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  slotLevelLabel: {
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "var(--color-muted)",
    minWidth: "28px",
  },
  slotDots: {
    display: "flex",
    gap: "0.3rem",
    flex: 1,
  },
  slotDot: {
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,0.12)",
    cursor: "pointer",
    padding: 0,
    transition: "background 0.15s ease",
  },
  slotCount: {
    fontSize: "0.7rem",
    color: "var(--color-muted)",
    minWidth: "30px",
    textAlign: "right",
  },
  /* Spell Add */
  spellAddRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  /* Spell List */
  spellEmpty: {
    textAlign: "center",
    color: "var(--color-muted)",
    fontSize: "0.8rem",
    padding: "2rem 0",
  },
  spellList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  spellGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  spellGroupHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.25rem 0",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
  },
  spellGroupTitle: {
    fontSize: "0.8rem",
    fontWeight: 700,
    color: "var(--color-muted)",
  },
  spellGroupCount: {
    fontSize: "0.7rem",
    color: "var(--color-muted)",
    background: "rgba(255,255,255,0.05)",
    padding: "0.1rem 0.4rem",
    borderRadius: "8px",
  },
  spellCard: {
    borderRadius: "6px",
    overflow: "hidden",
  },
  spellCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.6rem 0.75rem",
    cursor: "pointer",
    gap: "0.5rem",
  },
  spellCardLeft: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    flex: 1,
    minWidth: 0,
  },
  spellCardInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "0.1rem",
    minWidth: 0,
  },
  spellCardName: {
    fontSize: "0.85rem",
    fontWeight: 700,
    color: "var(--color-text)",
  },
  spellCardMeta: {
    fontSize: "0.65rem",
    color: "var(--color-muted)",
  },
  spellCardActions: {
    display: "flex",
    alignItems: "center",
    gap: "0.4rem",
    flexShrink: 0,
  },
  expandIcon: {
    fontSize: "0.6rem",
    color: "var(--color-muted)",
  },
  spellDetail: {
    borderTop: "1px solid rgba(255,255,255,0.06)",
    padding: "0.6rem 0.75rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  spellMetaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "0.35rem",
  },
  spellMetaItem: {
    display: "flex",
    flexDirection: "column",
    gap: "0.1rem",
  },
  spellMetaLabel: {
    fontSize: "0.6rem",
    color: "var(--color-muted)",
    fontWeight: 600,
  },
  spellMetaVal: {
    fontSize: "0.75rem",
    color: "var(--color-text)",
  },
  spellDescSection: {
    display: "flex",
    flexDirection: "column",
    gap: "0.2rem",
  },
  spellDescLabel: {
    fontSize: "0.65rem",
    color: "var(--color-muted)",
    fontWeight: 600,
  },
  spellDescText: {
    fontSize: "0.78rem",
    color: "var(--color-text)",
    lineHeight: 1.4,
  },
};

export { styles };
